services:
  ros2-simulation:
    image: ros2-vnc
    user: user
    container_name: ros2-simulation
    ports:
      - "8080:8080"
      - "5900:5900"
      - "1880:1880"
    shm_size: "2g"
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: bash -c '/usr/bin/supervisord -c /home/user/supervisor/supervisord.conf'
    volumes:
      - ./workspace:/home/user/workspace
      # - node_red_user_data:/data:rw
    networks:
      - eduart-net

networks:
  eduart-net:
    driver: bridge

# volumes:
 #   node_red_user_data: